server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://localhost/accountancy?useSSL=false
    username: tamara
    password: nacs
  jpa:
    hibernate:
      ddl-auto: update

dataset:
  costs:
    call family: 0.5
    hang out with friends: 14.0
    a night out with lots of fun: 25.5
    love: 100.0
    happiness: 1000.0
    positivity: 5.5
    friends: 0.5
    family: 101.2
